### ISSUE TITLE
'Namespace' object has no attribute 'safe'

### ISSUE THREAD

**Issue by kjcsb1** [bikeshedder/tusker-python-legacy#27]
Steps to reproduce:
```
tusker clean
Traceback (most recent call last):
  File "/home/kjcsb1/.local/bin/tusker", line 8, in <module>
    sys.exit(main())
  File "/home/kjcsb1/.local/pipx/venvs/tusker/lib/python3.8/site-packages/tusker/__init__.py", line 385, in main
    if getattr(args, 'safe') is not None:
AttributeError: 'Namespace' object has no attribute 'safe'
```

Version
```
tusker --version
tusker 0.5.0
```

Config
```
[schema]
filename = "db/init/*/*.sql"

[migrations]
filename = "db/migrations/*.sql"

[database]
url = "postgresql://postgres:kjcsb1@1.2.3.4:5432/postgres"

[migra]
safe = true
privileges = false
```

**Comment by bikeshedder** [comment]
That's pretty weird. I was unable to reproduce this error but have decided to change the call from `getattr(args, 'safe')` to `getattr(args, 'safe', None)`. I'll release `tusker 0.5.1` including this fix shortly.

**Comment by bikeshedder** [comment]
Please give `tusker 0.5.1` a try. This version should fix the issue you ran into: https://pypi.org/project/tusker/0.5.1/
