### ISSUE TITLE
Missing dependency in pip package

### ISSUE THREAD

**Issue by abijr** [bikeshedder/tusker-python-legacy#8]
After installing using `pip3 install tusker` I get this error
```
tusker --help
Traceback (most recent call last):
  File "/home/potemkin/.asdf/installs/python/3.9.0/bin/tusker", line 5, in <module>
    from tusker import main
  File "/home/potemkin/.asdf/installs/python/3.9.0/lib/python3.9/site-packages/tusker/__init__.py", line 11, in <module>
    import migra
  File "/home/potemkin/.asdf/installs/python/3.9.0/lib/python3.9/site-packages/migra/__init__.py", line 3, in <module>
    from .changes import Changes
  File "/home/potemkin/.asdf/installs/python/3.9.0/lib/python3.9/site-packages/migra/changes.py", line 6, in <module>
    import schemainspect
  File "/home/potemkin/.asdf/installs/python/3.9.0/lib/python3.9/site-packages/schemainspect/__init__.py", line 4, in <module>
    from .command import do_command
  File "/home/potemkin/.asdf/installs/python/3.9.0/lib/python3.9/site-packages/schemainspect/command.py", line 4, in <module>
    from sqlbag import S
  File "/home/potemkin/.asdf/installs/python/3.9.0/lib/python3.9/site-packages/sqlbag/__init__.py", line 11, in <module>
    from .misc import (
  File "/home/potemkin/.asdf/installs/python/3.9.0/lib/python3.9/site-packages/sqlbag/misc.py", line 7, in <module>
    from .sqla import raw_execute
  File "/home/potemkin/.asdf/installs/python/3.9.0/lib/python3.9/site-packages/sqlbag/sqla.py", line 8, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

It goes away if I install `packaging`.

**Comment by bikeshedder** [comment]
`tusker` doesn't use `packaging` directly. I think this is an error of the `sqlbag` dependency?
